[build]
  publish = "public/"
  command = "yarn run netlify:build"

[build.environment]
	CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
	TERM = "xterm"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
	package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false
  [plugins.inputs.postBuild]
    enable = true
    start = 'yarn run netlify:test'
    wait-on = 'http://localhost:8000'
    wait-on-timeout = '30'

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.8
    best-practices = 0.8
    seo = 0.8
  [plugins.inputs.audits]
    output_path = "public/reports/lighthouse.html"

