backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
editor:
    preview: true
site_url: https://www.torystories.stream
collections:
    - name: episodes
      label: Episodes
      folder: content/episodes
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Episode number
            name: episodeNum
            widget: number
            min: 1
            value_type: 'int'
            required: true
          - label: Publish Date
            name: date
            widget: datetime
            required: true
          - label: SEO Description
            name: description
            widget: string
            required: false
          - label: Episode Image
            name: featuredImage
            widget: image
            required: false
          - label: Audio file
            name: audioFile
            widget: file
            required: true
          - label: Syndication Links
            name: syndicationLinks
            widget: list
            field: { label: Link, name: link, widget: string }
            min: 0
          - label: Subtitles File
            name: subtitles
            widget: file
            required: false
          - label: Episode Blurb
            name: body
            widget: markdown
            required: true
    - name: misc
      label: Misc Content
      folder: content/misc
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      fields:
          - label: Name
            name: title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            required: false
