name: Automatically merge automerge PR's
'on':
  pull_request:
    types:
      - opened
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          MERGE_LABELS: 'automerge'
          GITHUB_TOKEN: '${{ secrets.REPO_GITHUB_TOKEN }}'
