---
name: Create PR from dev branch with automerge tag
'on':
  push:
    branches:
      - dev
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: automerge
