---
name: Run E2E tests on new code in master
'on':
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 360

      - name: Upload E2E run data as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-run-data
          path: |
            /home/runner/work/torystories.stream/torystories.stream/cypress/screenshots/*
            /home/runner/work/torystories.stream/torystories.stream/cypress/videos/*
          retention-days: 14

      - name: Push changes to cloudflare if success
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          branch: cloudflare
          force: true
